# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""
from evo_rlt.adapters.lerobot.franka_robot import FrankaRobotConfig, FrankaRobot  # noqa: F401

import inspect
import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.feature_utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.io_utils import write_info
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.processor import make_default_processors
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from evo_rlt.adapters.lerobot.record.hil import (
    ACPInferenceConfig,
    PolicySyncDualArmExecutor,
    _capture_policy_runtime_state,  # noqa: F401
    _predict_policy_action_with_acp_inference,  # noqa: F401
)
from evo_rlt.adapters.lerobot.record.loop import (
    manual_demo_health_tick,
    new_health_state,
    process_gripper_key_events,
    record_loop,
    record_manual_demo_loop,
)
from lerobot.teleoperators import (  # noqa: F401
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from evo_rlt.adapters.lerobot.record.annotations import (
    COLLECTOR_HUMAN,
    COLLECTOR_POLICY,
    RLT_COLLECTOR_POLICY_ID_TO_NAME,
    infer_collector_policy_version,
    normalize_episode_success_label,
    resolve_episode_success_label,
)
from lerobot.utils.device_utils import get_safe_torch_device
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to >=1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Encode videos in real time during capture instead of writing PNGs first.
    # This keeps save_episode() from blocking the foreground recording loop.
    streaming_encoding: bool = True
    # Maximum number of frames to buffer per camera when using streaming encoding.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None uses the codec default.
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)
    # Record observations with zero actions and without commanding the robot.
    # Passive static smoke-test mode: requires no policy/teleoperator.
    zero_action_mode: bool = False
    # Real manual-demonstration recording: the operator guides the FR3 by hand
    # (Desk Programming/Guiding mode), presses ENTER to start an episode, RIGHT
    # to end and save it, LEFT to discard and re-record. The recorder only
    # reads state (wrist+front RGB, joints, joint velocities, TCP pose, gripper)
    # and writes the measured 6D TCP delta plus next measured gripper width; it
    # never sends arm-motion commands to the robot.
    # Requires no policy/teleoperator and must not be combined with zero_action_mode.
    manual_demo_mode: bool = False
    # Manual-demo keyboard control of the Franka Hand: while an episode records
    # AND in the idle windows between episodes the operator can force-grasp with
    # `manual_demo_gripper_close_key` and open with `manual_demo_gripper_open_key`.
    # Single characters, case-insensitive; only meaningful when manual_demo_mode
    # is on a Franka. Commands are blocking RPCs to the control server, run on
    # the recording thread (see record.loop.process_gripper_key_events).
    manual_demo_gripper_close_key: str = "c"
    manual_demo_gripper_open_key: str = "o"

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")
        if self.zero_action_mode and self.manual_demo_mode:
            raise ValueError("`zero_action_mode` and `manual_demo_mode` are mutually exclusive.")
        if self.manual_demo_mode:
            for key_name, key_value in (
                ("manual_demo_gripper_close_key", self.manual_demo_gripper_close_key),
                ("manual_demo_gripper_open_key", self.manual_demo_gripper_open_key),
            ):
                if not key_value or len(key_value) != 1:
                    raise ValueError(f"`{key_name}` must be a single character.")
            if self.manual_demo_gripper_close_key.lower() == self.manual_demo_gripper_open_key.lower():
                raise ValueError(
                    "`manual_demo_gripper_close_key` and `manual_demo_gripper_open_key` must be distinct."
                )


@dataclass
class RLTRecordConfig:
    enable: bool = False
    critical_phase_toggle_key: str = "p"
    default_reset_mode: str = "full"
    # RLT deploy settings (used when enable=True)
    vla_model: str = ""
    rl_token_ckpt: str = ""
    ac_ckpt: str = ""
    task_instruction: str = ""
    phase_mode: str = "manual"
    device: str = "cuda"
    chunk_length: int = 10
    chunk_exec_steps: int = 25
    token_pool_size: int = 64
    image_only: bool = False
    deterministic: bool = True
    actor_hidden_dim: int = 256
    actor_num_layers: int = 3
    actor_residual: bool = True
    actor_activation: str = "relu"
    actor_layer_norm: bool = False
    # Keyboard keys for RLT HIL mode
    rl_phase_key: str = "r"
    end_success_key: str = "s"
    end_failure_key: str = "f"
    # wo_prefix mode: drop frames captured during PHASE_PREFIX (before RL phase
    # starts). Used when the dataset should only contain the RL-driven segment.
    skip_prefix_recording: bool = False
    # wo_prefix mode: rl_phase_key toggles - first press starts the episode (and
    # RL phase), second press ends the episode (sets exit_early). Single end
    # press marks the episode as success; a follow-up press inside
    # `rl_phase_double_tap_window_s` marks it as failure.
    rl_phase_key_toggles_episode: bool = False
    # With-prefix mode: rl_phase_key toggles the critical phase only - first
    # press starts RL, second press ends RL and marks the critical phase
    # (success by default, failure if a second press lands inside the
    # double-tap window). Episode keeps going in VLA mode afterwards.
    rl_phase_key_toggles_critical_phase: bool = False
    rl_phase_double_tap_window_s: float = 0.6
    # wo_prefix mode: start each episode in human-teleop state (leader drives
    # follower, no policy actions sent) until the user presses the rl_phase_key
    # to enter RL. Required for pure RL-only HIL recording where VLA should
    # never drive the robot.
    start_in_teleop: bool = False
    # Blend follower commands from the last policy action to teleop during
    # SPACE handoff, reducing one-frame jumps when the leader is released.
    intervention_action_blend_time_s: float = 0.0
    # RTC deploy settings for rlt_ac. Disabled by default so existing record
    # scripts keep the synchronous chunk queue.
    rtc_enabled: bool = False
    rtc_execution_horizon: int = 10
    vla_rtc_execution_horizon: int | None = None
    rtc_max_guidance_weight: float = 10.0
    rtc_prefix_attention_schedule: str = "EXP"
    rtc_action_queue_size_to_get_new_actions: int | None = None


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # In policy mode, broadcast the same robot action to the teleop arm via `teleop.send_feedback`.
    policy_sync_to_teleop: bool = False
    # Use parallel dispatch to reduce action broadcast latency when syncing policy to teleop.
    policy_sync_parallel: bool = True
    # Enable S0/S1/S2 intervention state machine when policy + teleop are both available.
    intervention_state_machine_enabled: bool = True
    # Keyboard key used to toggle entering/leaving intervention.
    intervention_toggle_key: str = "i"
    # Pure-teleop mode: r key starts an episode (entering critical phase),
    # second r press ends the episode and marks it success; a double-tap
    # inside `rlt.rl_phase_double_tap_window_s` marks it failure. No VLA,
    # no RL inference, no SPACE intervention - teleop drives the entire
    # time, r is the only episode-control input. Requires policy to be
    # None (teleop-only) and reuses the same underlying state machine as
    # the rlt wo_prefix recorder.
    teleop_r_key_episodes: bool = False
    # Whether to capture episode-level success/failure labels from keyboard.
    enable_episode_outcome_labeling: bool = False
    # Keyboard key to mark the current episode as success and end it.
    episode_success_key: str = "s"
    # Keyboard key to mark the current episode as failure and end it.
    episode_failure_key: str = "f"
    # Optional fallback label used when no explicit success/failure key was pressed.
    default_episode_success: str | None = None
    # If True, require explicit or default episode labels before saving.
    require_episode_success_label: bool = False
    # Unified schema always records step-level collector source ids.
    enable_collector_policy_id: bool = True
    # Numeric code used when the executed action comes from the primary policy.
    collector_policy_id_policy: int = COLLECTOR_POLICY
    # Numeric code used when the executed action comes from human teleoperation.
    collector_policy_id_human: int = COLLECTOR_HUMAN
    # ACP inference controls for policy-driven recording.
    acp_inference: ACPInferenceConfig = field(default_factory=ACPInferenceConfig)
    # Retry timeout for transient communication errors (seconds). Set to 0 to fail immediately.
    communication_retry_timeout_s: float = 2.0
    # Sleep interval between communication retries (seconds).
    communication_retry_interval_s: float = 0.1
    # Enable critical phase labeling via keyboard toggle during recording.
    enable_critical_phase_labeling: bool = False
    # Keyboard key for toggling critical phase marking. Default is space.
    critical_phase_toggle_key: str = " "
    rlt: RLTRecordConfig = field(default_factory=RLTRecordConfig)
    # Path to a JSON file with robot + camera config (e.g. roboclaw setup.json).
    # When set, overrides robot port and camera CLI args.
    robot_config_file: str | None = None
    # If False, the rlt_ac actor receives a zeroed VLA reference chunk at
    # inference (mirrors training ref-dropout). RL phase only; VLA passthrough
    # and non-rlt_ac policies are unaffected.
    vla_ref: bool = True

    def __post_init__(self):
        if self.robot_config_file is not None:
            from evo_rlt.adapters.lerobot.record.robot_config import load_robot_config_from_json

            self.robot = load_robot_config_from_json(self.robot_config_file)

        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        # When RLT is enabled, translate RLT config into a standard RLT policy config
        if self.rlt.enable and self.rlt.vla_model and self.policy is None:
            from evo_rlt.adapters.lerobot.policies.configuration_rlt import RLTPretrainedConfig

            self.policy = RLTPretrainedConfig(
                vla_pretrained_path=self.rlt.vla_model,
                rl_token_ckpt_path=self.rlt.rl_token_ckpt,
                ac_ckpt_path=self.rlt.ac_ckpt,
                task_instruction=self.rlt.task_instruction or self.dataset.single_task,
                phase_mode=self.rlt.phase_mode,
                device=self.rlt.device,
                chunk_length=self.rlt.chunk_length,
                chunk_exec_steps=self.rlt.chunk_exec_steps,
                token_pool_size=self.rlt.token_pool_size,
                image_only=self.rlt.image_only,
                deterministic=self.rlt.deterministic,
                actor_hidden_dim=self.rlt.actor_hidden_dim,
                actor_num_layers=self.rlt.actor_num_layers,
                actor_residual=self.rlt.actor_residual,
                actor_activation=self.rlt.actor_activation,
                actor_layer_norm=self.rlt.actor_layer_norm,
            )
            # preprocessor/postprocessor come from VLA model directory
            self.policy.pretrained_path = self.rlt.vla_model

        if (
            self.teleop is None
            and self.policy is None
            and not self.dataset.zero_action_mode
            and not self.dataset.manual_demo_mode
        ):
            raise ValueError(
                "Choose a policy, a teleoperator, or enable RLT/zero_action_mode/manual_demo_mode to control the robot"
            )
        if not self.intervention_toggle_key or len(self.intervention_toggle_key) != 1:
            raise ValueError("`intervention_toggle_key` must be a single character.")

        if self.enable_episode_outcome_labeling:
            label_key_bindings = {
                "episode_success_key": self.episode_success_key,
                "episode_failure_key": self.episode_failure_key,
            }
            for key_name, key_value in label_key_bindings.items():
                if not key_value or len(key_value) != 1:
                    raise ValueError(f"`{key_name}` must be a single character.")

            normalized_keys = [
                self.intervention_toggle_key.lower(),
                self.episode_success_key.lower(),
                self.episode_failure_key.lower(),
            ]
            if len(set(normalized_keys)) != len(normalized_keys):
                raise ValueError(
                    "`intervention_toggle_key`, `episode_success_key`, and `episode_failure_key` must be distinct."
                )

        if self.rlt.enable:
            if not self.rlt.critical_phase_toggle_key or len(self.rlt.critical_phase_toggle_key) != 1:
                raise ValueError("`rlt.critical_phase_toggle_key` must be a single character.")

            reserved_keys = [
                self.rlt.critical_phase_toggle_key.lower(),
                self.intervention_toggle_key.lower(),
            ]
            if self.enable_episode_outcome_labeling:
                reserved_keys.append(self.episode_success_key.lower())
                reserved_keys.append(self.episode_failure_key.lower())
            if len(set(reserved_keys)) != len(reserved_keys):
                raise ValueError(
                    "`rlt.critical_phase_toggle_key` must not collide with intervention or episode outcome keys."
                )

        if self.default_episode_success is not None:
            self.default_episode_success = normalize_episode_success_label(self.default_episode_success)

        if not self.enable_collector_policy_id:
            raise ValueError("`enable_collector_policy_id` must stay true for the unified recording schema.")
        if self.collector_policy_id_human < 0:
            raise ValueError("`collector_policy_id_human` must be >= 0.")
        if self.collector_policy_id_policy < 0:
            raise ValueError("`collector_policy_id_policy` must be >= 0.")
        if self.collector_policy_id_human == self.collector_policy_id_policy:
            raise ValueError("`collector_policy_id_human` and `collector_policy_id_policy` must be distinct.")
        if self.acp_inference.use_cfg and not self.acp_inference.enable:
            raise ValueError("`acp_inference.use_cfg=true` requires `acp_inference.enable=true`.")
        if self.acp_inference.cfg_beta < 0:
            raise ValueError("`acp_inference.cfg_beta` must be >= 0.")
        if self.communication_retry_timeout_s < 0:
            raise ValueError("`communication_retry_timeout_s` must be >= 0.")
        if self.communication_retry_interval_s <= 0:
            raise ValueError("`communication_retry_interval_s` must be > 0.")
        if self.rlt.intervention_action_blend_time_s < 0:
            raise ValueError("`rlt.intervention_action_blend_time_s` must be >= 0.")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


def _accepts_kwarg(fn, name: str) -> bool:
    params = inspect.signature(fn).parameters
    return name in params or any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values())


def _start_manual_demo_keyboard_listener(
    gripper_close_key: str = "c",
    gripper_open_key: str = "o",
):
    """Build the pynput keyboard listener driving manual-demonstration episodes.

    Returns ``(listener, events)``. All bindings fire on key press:

      - Enter -> ``events["start_episode"]``      begin recording the next episode
      - Right -> ``events["exit_early"]``         end the current episode and save it
      - Left  -> ``events["rerecord_episode"]`` + ``exit_early``  discard, re-record
      - Esc   -> ``events["stop_recording"]`` + ``exit_early``    quit everything
      - ``gripper_close_key`` (default ``c``) -> ``events["close_gripper"]``  grasp the Hand
      - ``gripper_open_key``  (default ``o``) -> ``events["open_gripper"]``   open the Hand

    Gripper events are one-shot flags consumed on the recording thread by
    ``record.loop.process_gripper_key_events`` (blocking RPCs must not run on
    the pynput thread).
    """
    if is_headless():
        raise RuntimeError(
            "manual_demo_mode needs a physical keyboard: ENTER starts an episode, RIGHT "
            "ends & saves it, LEFT discards it, ESC quits, "
            f"{gripper_close_key.upper()} closes the gripper, {gripper_open_key.upper()} opens it. "
            "The session is headless."
        )
    from pynput import keyboard

    gripper_close_key = gripper_close_key.lower()
    gripper_open_key = gripper_open_key.lower()

    events = {
        "start_episode": False,
        "exit_early": False,
        "rerecord_episode": False,
        "stop_recording": False,
        "episode_outcome": None,
        "close_gripper": False,
        "open_gripper": False,
    }

    def _is_char_key(key, target: str) -> bool:
        return (
            isinstance(key, keyboard.KeyCode)
            and key.char is not None
            and key.char.lower() == target
        )

    def on_press(key) -> None:
        if key == keyboard.Key.enter:
            events["start_episode"] = True
            logging.info("manual-demo key: ENTER -> start episode")
        elif key == keyboard.Key.right:
            events["exit_early"] = True
            logging.info("manual-demo key: RIGHT -> end episode and save")
        elif key == keyboard.Key.left:
            events["exit_early"] = True
            events["rerecord_episode"] = True
            logging.info("manual-demo key: LEFT -> discard episode, re-record")
        elif key == keyboard.Key.esc:
            events["exit_early"] = True
            events["stop_recording"] = True
            logging.info("manual-demo key: ESC -> stop recording")
        elif _is_char_key(key, gripper_close_key):
            events["close_gripper"] = True
            logging.info("manual-demo key: %s -> close gripper", gripper_close_key)
        elif _is_char_key(key, gripper_open_key):
            events["open_gripper"] = True
            logging.info("manual-demo key: %s -> open gripper", gripper_open_key)

    listener = keyboard.Listener(on_press=on_press)
    listener.start()
    return listener, events


def _ensure_human_inloop_compatible_features(
    dataset_features: dict[str, dict],
    *,
    action_feature_names: list[str],
) -> None:
    # Unified annotation schema shared by future recorded datasets.
    dataset_features["complementary_info.policy_action"] = {
        "dtype": "float32",
        "shape": (len(action_feature_names),),
        "names": action_feature_names,
    }
    dataset_features["complementary_info.is_intervention"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["is_intervention"],
    }
    dataset_features["complementary_info.state"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["state"],
    }
    dataset_features["complementary_info.phase"] = {"dtype": "float32", "shape": (1,), "names": ["phase"]}


def _add_collector_policy_id_feature(dataset_features: dict[str, dict]) -> None:
    dataset_features["complementary_info.collector_policy_id"] = {
        "dtype": "int64",
        "shape": (1,),
        "names": ["collector_policy_id"],
    }


def _build_collector_policy_id_codebook(cfg: RecordConfig) -> dict[str, str]:
    if cfg.rlt.enable:
        return {str(code): name for code, name in RLT_COLLECTOR_POLICY_ID_TO_NAME.items()}
    if cfg.policy is None:
        return {str(cfg.collector_policy_id_human): "human"}
    return {
        str(cfg.collector_policy_id_human): "human",
        str(cfg.collector_policy_id_policy): infer_collector_policy_version(cfg.policy),
    }


def _write_schema_metadata(
    dataset: LeRobotDataset,
    *,
    collector_policy_id_codebook: dict[str, str],
    include_rlt_episode_metadata: bool,
) -> None:
    collector_info = dataset.meta.info["features"].get("complementary_info.collector_policy_id")
    if collector_info is None:
        return
    collector_info["info"] = {"codebook": collector_policy_id_codebook}
    if include_rlt_episode_metadata:
        dataset.meta.info["rlt_episode_metadata_fields"] = {
            "rl_intervals": "List of {start_frame, end_frame, outcome} for each RL phase.",
            "human_intervention_intervals": "List of {start_frame, end_frame} for each human intervention segment.",
        }
    dataset.meta.info["recording_schema_version"] = 2
    write_info(dataset.meta.info, dataset.root)


def _configure_rlt_record_policy(policy, cfg: RecordConfig) -> None:
    from evo_rlt.adapters.lerobot.policies.modeling_rlt_ac import ChunkACPolicy

    if not isinstance(policy, ChunkACPolicy):
        return
    policy.vla_ref = cfg.vla_ref
    logging.info("rlt_ac vla_ref=%s (False => zeroed VLA reference chunk)", cfg.vla_ref)
    if not cfg.rlt.rtc_enabled:
        return

    from lerobot.configs.types import RTCAttentionSchedule
    from lerobot.policies.rtc.configuration_rtc import RTCConfig

    schedule = RTCAttentionSchedule(cfg.rlt.rtc_prefix_attention_schedule)
    rtc_config = RTCConfig(
        enabled=True,
        execution_horizon=cfg.rlt.rtc_execution_horizon,
        max_guidance_weight=cfg.rlt.rtc_max_guidance_weight,
        prefix_attention_schedule=schedule,
    )
    vla_rtc_config = None
    if cfg.rlt.vla_rtc_execution_horizon is not None:
        vla_rtc_config = RTCConfig(
            enabled=True,
            execution_horizon=cfg.rlt.vla_rtc_execution_horizon,
            max_guidance_weight=cfg.rlt.rtc_max_guidance_weight,
            prefix_attention_schedule=schedule,
        )
    policy.configure_rtc(
        rtc_config,
        fps=cfg.dataset.fps,
        action_queue_size_to_get_new_actions=cfg.rlt.rtc_action_queue_size_to_get_new_actions,
        vla_rtc_config=vla_rtc_config,
    )
    logging.info(
        "rlt_ac RTC enabled: rlt_horizon=%d vla_horizon=%d guidance=%.3f schedule=%s refill_threshold=%s",
        cfg.rlt.rtc_execution_horizon,
        cfg.rlt.vla_rtc_execution_horizon or cfg.rlt.rtc_execution_horizon,
        cfg.rlt.rtc_max_guidance_weight,
        cfg.rlt.rtc_prefix_attention_schedule,
        cfg.rlt.rtc_action_queue_size_to_get_new_actions,
    )


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    if cfg.require_episode_success_label and not cfg.enable_episode_outcome_labeling:
        raise ValueError(
            "`require_episode_success_label=true` requires `enable_episode_outcome_labeling=true`."
        )
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )
    action_names = dataset_features[ACTION]["names"]
    action_names = list(robot.action_features) if action_names is None else list(action_names)
    _ensure_human_inloop_compatible_features(dataset_features, action_feature_names=action_names)
    if cfg.enable_collector_policy_id:
        _add_collector_policy_id_feature(dataset_features)

    dataset = None
    listener = None
    policy_sync_executor = None
    critical_phase_tracker = None
    intervention_tracker = None

    try:
        if cfg.resume:
            camera_count = len(robot.cameras) if hasattr(robot, "cameras") else 0
            dataset = LeRobotDataset.resume(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                image_writer_processes=(
                    cfg.dataset.num_image_writer_processes if camera_count else 0
                ),
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * camera_count,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )
        _write_schema_metadata(
            dataset,
            collector_policy_id_codebook=_build_collector_policy_id_codebook(cfg),
            include_rlt_episode_metadata=cfg.rlt.enable,
        )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        _configure_rlt_record_policy(policy, cfg)
        preprocessor = None
        postprocessor = None
        if cfg.acp_inference.enable and cfg.policy is None:
            raise ValueError("`acp_inference.enable=true` requires `policy` to be set.")
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        collector_policy_id_policy = cfg.collector_policy_id_policy
        collector_policy_id_human = cfg.collector_policy_id_human

        robot.connect()
        if teleop is not None:
            teleop.connect()
        on_record_connected = getattr(cfg, "_on_record_connected", None)
        if callable(on_record_connected):
            on_record_connected(robot, teleop)

        if cfg.policy_sync_to_teleop:
            if cfg.policy is None:
                raise ValueError("`policy_sync_to_teleop=true` requires `policy` to be set.")
            if teleop is None or isinstance(teleop, list):
                raise ValueError(
                    "`policy_sync_to_teleop=true` requires exactly one teleoperator with send_feedback support."
                )
            policy_sync_executor = PolicySyncDualArmExecutor(
                robot=robot,
                teleop=teleop,
                parallel_dispatch=cfg.policy_sync_parallel,
            )

        critical_phase_tracker = None
        teleop_r_key_mode = cfg.teleop_r_key_episodes and policy is None
        if (
            cfg.enable_critical_phase_labeling
            or (cfg.rlt.enable and cfg.rlt.vla_model)
            or teleop_r_key_mode
        ):
            from lerobot.utils.critical_phase_tracker import CriticalPhaseTracker, EpisodeIntervalTracker

            critical_phase_tracker = CriticalPhaseTracker(
                auto_save_path=dataset.root / "critical_phase_intervals.json",
            )
            if cfg.rlt.enable:
                intervention_tracker = EpisodeIntervalTracker(label="Human intervention")

        # RLT policy is now a standard PreTrainedPolicy - no separate instantiation needed

        cp_key = cfg.critical_phase_toggle_key if cfg.enable_critical_phase_labeling else None
        if cp_key is None and cfg.rlt.enable:
            cp_key = cfg.rlt.critical_phase_toggle_key

        # RLT HIL mode: use SPACE for intervention, r/s/f for phase control
        rlt_hil_mode = cfg.rlt.enable and policy is not None and teleop is not None
        rlt_active = cfg.rlt.enable and policy is not None
        rlt_key_controls_phase = (
            cfg.rlt.rl_phase_key_toggles_episode or cfg.rlt.rl_phase_key_toggles_critical_phase
        )
        if rlt_active and rlt_key_controls_phase:
            rl_phase_key_binding = cfg.rlt.rl_phase_key
        elif teleop_r_key_mode:
            rl_phase_key_binding = "r"
        else:
            rl_phase_key_binding = None
        # In teleop_r_key_mode the r key is the single episode-control input;
        # unbind s/f so the user cannot accidentally end an episode out of
        # the double-tap state machine.
        bind_ep_outcome_keys = cfg.enable_episode_outcome_labeling and not teleop_r_key_mode
        listener_kwargs = dict(
            intervention_toggle_key=" " if rlt_hil_mode else cfg.intervention_toggle_key,
            critical_phase_toggle_key=cp_key if not rlt_active else None,
            episode_success_key=cfg.episode_success_key if bind_ep_outcome_keys else None,
            episode_failure_key=cfg.episode_failure_key if bind_ep_outcome_keys else None,
            cp_success_key="s" if cfg.enable_critical_phase_labeling and not rlt_active else None,
            cp_failure_key="f" if cfg.enable_critical_phase_labeling and not rlt_active else None,
            rl_phase_key=rl_phase_key_binding,
            end_success_key=cfg.rlt.end_success_key if rlt_active else None,
            end_failure_key=cfg.rlt.end_failure_key if rlt_active else None,
        )
        # One health-watchdog dict per recording session, shared by every take
        # and the idle windows between them, so a latched control-server/camera
        # fault blocks the next take too. (Only manual_demo_mode uses it; the
        # RLT/HIL pipeline has its own interruption semantics.)
        health = new_health_state()
        if cfg.dataset.manual_demo_mode:
            if teleop is not None or policy is not None:
                raise ValueError(
                    "`dataset.manual_demo_mode=true` requires no `policy` and no `teleop`: the arm "
                    "is guided by hand and the recorder only reads state (never sends servo commands)."
                )
            listener, events = _start_manual_demo_keyboard_listener(
                gripper_close_key=cfg.dataset.manual_demo_gripper_close_key,
                gripper_open_key=cfg.dataset.manual_demo_gripper_open_key,
            )
        elif _accepts_kwarg(init_keyboard_listener, "intervention_toggle_key"):
            listener, events = init_keyboard_listener(**listener_kwargs)
        else:
            # lerobot >= 0.5: base init_keyboard_listener() takes no arguments and only
            # binds right/left/esc. Fall back only when no extended key bindings are
            # requested; otherwise fail loudly instead of silently degrading
            # RLT/HIL key controls.
            intervention_keys_needed = (
                cfg.intervention_state_machine_enabled and policy is not None and teleop is not None
            )
            extended_keys_requested = any(
                (
                    intervention_keys_needed,
                    cfg.enable_critical_phase_labeling,
                    cfg.rlt.enable,
                    bind_ep_outcome_keys,
                    teleop_r_key_mode,
                )
            )
            if extended_keys_requested:
                raise ValueError(
                    "Extended keyboard bindings are requested (RLT / critical phase / episode "
                    "outcome labeling / intervention / teleop r-key episodes), but the installed "
                    "lerobot's init_keyboard_listener does not accept key-binding arguments. "
                    "Use a lerobot version with the extended listener, or disable these features."
                )
            listener, events = init_keyboard_listener()

        def _warmup_rlt_path() -> None:
            if not (rlt_active and policy is not None and preprocessor is not None and postprocessor is not None):
                return
            log_say("Warming up RL path", cfg.play_sounds)
            warmup_obs = robot.get_observation()
            warmup_obs_processed = robot_observation_processor(warmup_obs)
            warmup_frame = build_dataset_frame(dataset.features, warmup_obs_processed, prefix=OBS_STR)
            if hasattr(policy, "set_rl_mode"):
                policy.set_rl_mode()
            _predict_policy_action_with_acp_inference(
                observation_frame=warmup_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=cfg.dataset.single_task,
                robot_type=robot.robot_type,
                acp_inference=cfg.acp_inference,
            )
            log_say("Ready", cfg.play_sounds)

        def _start_episode_trackers() -> None:
            if critical_phase_tracker is not None:
                critical_phase_tracker.on_episode_start(dataset.num_episodes)
            if intervention_tracker is not None:
                intervention_tracker.on_episode_start(dataset.num_episodes)

        def _reset_policy_for_episode() -> None:
            if policy is not None and hasattr(policy, "set_rl_mode"):
                policy.reset()

        def _record_episode() -> None:
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                display_compressed_images=display_compressed_images,
                policy_sync_executor=policy_sync_executor,
                intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                collector_policy_id_policy=collector_policy_id_policy,
                collector_policy_id_human=collector_policy_id_human,
                acp_inference=cfg.acp_inference,
                communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                communication_retry_interval_s=cfg.communication_retry_interval_s,
                critical_phase_tracker=critical_phase_tracker,
                rlt_intervention_tracker=intervention_tracker,
                skip_prefix_recording=cfg.rlt.skip_prefix_recording or teleop_r_key_mode,
                rl_phase_key_toggles_episode=cfg.rlt.rl_phase_key_toggles_episode or teleop_r_key_mode,
                rl_phase_key_toggles_critical_phase=cfg.rlt.rl_phase_key_toggles_critical_phase,
                rl_phase_double_tap_window_s=cfg.rlt.rl_phase_double_tap_window_s,
                start_in_teleop=cfg.rlt.start_in_teleop,
                intervention_action_blend_time_s=cfg.rlt.intervention_action_blend_time_s,
                zero_action_mode=cfg.dataset.zero_action_mode,
            )

        def _current_episode_frame_count() -> int:
            writer = getattr(dataset, "writer", None)
            episode_buffer = getattr(writer, "episode_buffer", None)
            return episode_buffer["size"] if episode_buffer else 0

        def _finish_episode_trackers() -> None:
            ep_frames = _current_episode_frame_count()
            if critical_phase_tracker is not None:
                critical_phase_tracker.on_episode_end(ep_frames)
            if intervention_tracker is not None:
                intervention_tracker.on_episode_end(ep_frames)

        def _resolve_current_episode_success() -> str | None:
            if not cfg.enable_episode_outcome_labeling:
                return None
            episode_success = resolve_episode_success_label(
                explicit_label=events.get("episode_outcome"),
                default_label=cfg.default_episode_success,
                require_label=cfg.require_episode_success_label,
            )
            if events.get("episode_outcome") is None and episode_success is not None:
                logging.warning(
                    "Episode %s has no explicit success/failure label, defaulting to '%s'.",
                    dataset.num_episodes,
                    episode_success,
                )
            return episode_success

        def _notify_episode_outcome(episode_success: str | None) -> None:
            on_episode_outcome = getattr(cfg, "_on_record_episode_outcome", None)
            if callable(on_episode_outcome):
                on_episode_outcome(robot, teleop, episode_success)

        def _should_run_reset_loop(recorded_episodes: int) -> bool:
            next_episode_needed = recorded_episodes < cfg.dataset.num_episodes - 1
            return (
                not events["stop_recording"]
                and not cfg.rlt.start_in_teleop
                and not teleop_r_key_mode
                and (next_episode_needed or events["rerecord_episode"])
            )

        def _run_reset_loop_if_needed(recorded_episodes: int) -> None:
            if not _should_run_reset_loop(recorded_episodes):
                return
            log_say("Reset the environment", cfg.play_sounds)
            if robot.name == "unitree_g1":
                robot.reset()
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                control_time_s=cfg.dataset.reset_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                policy_sync_executor=policy_sync_executor,
                intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                collector_policy_id_policy=collector_policy_id_policy,
                collector_policy_id_human=collector_policy_id_human,
                acp_inference=cfg.acp_inference,
                communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                communication_retry_interval_s=cfg.communication_retry_interval_s,
            )

        def _discard_rerecord_episode() -> bool:
            if not events["rerecord_episode"]:
                return False
            log_say("Re-record episode", cfg.play_sounds)
            if critical_phase_tracker is not None:
                critical_phase_tracker.discard_episode(dataset.num_episodes)
            if intervention_tracker is not None:
                intervention_tracker.discard_episode(dataset.num_episodes)
            events["rerecord_episode"] = False
            events["exit_early"] = False
            events["episode_outcome"] = None
            dataset.clear_episode_buffer()
            return True

        def _extra_episode_metadata(episode_success: str | None) -> dict | None:
            extra_episode_metadata = {}
            if cfg.enable_episode_outcome_labeling:
                extra_episode_metadata["episode_success"] = episode_success
            if cfg.rlt.enable:
                episode_idx = dataset.num_episodes
                extra_episode_metadata["rl_intervals"] = (
                    critical_phase_tracker.serialize_episode_intervals(episode_idx)
                    if critical_phase_tracker is not None
                    else []
                )
                extra_episode_metadata["human_intervention_intervals"] = (
                    intervention_tracker.serialize_episode_intervals(episode_idx)
                    if intervention_tracker is not None
                    else []
                )
            return extra_episode_metadata or None

        def _finish_recorded_episode(recorded_episodes: int, episode_success: str | None) -> int:
            if _discard_rerecord_episode():
                return recorded_episodes
            extra_meta = _extra_episode_metadata(episode_success)
            if extra_meta is None:
                dataset.save_episode()
            elif _accepts_kwarg(dataset.save_episode, "extra_episode_metadata"):
                dataset.save_episode(extra_episode_metadata=extra_meta)
            else:
                raise RuntimeError(
                    "Episode metadata (outcome labeling / RLT intervals) was requested, but the "
                    "installed lerobot's save_episode does not accept extra_episode_metadata. "
                    "Use prepare_lerobot_runtime(background_episode_video_encoding=True) to "
                    "enable the patched path."
                )
            return recorded_episodes + 1

        def _record_manual_demo_episode() -> dict | None:
            # Human guiding: frames are buffered one-behind so each stored frame's
            # action is the measured 6D delta toward the next frame's TCP pose.
            return record_manual_demo_loop(
                robot=robot,
                dataset=dataset,
                events=events,
                fps=cfg.dataset.fps,
                single_task=cfg.dataset.single_task,
                control_time_s=cfg.dataset.episode_time_s,
                collector_policy_id_human=collector_policy_id_human,
                play_sounds=cfg.play_sounds,
                health=health,
            )

        def _run_manual_demo_episodes() -> int:
            """Run the reset/wait <-> record state machine for manual demos.

            Reset/wait windows are *not* recorded (no frame is added while waiting
            for ENTER). Only ENTER-started stretches are written; RIGHT saves,
            LEFT discards (no count), ESC stops. Returns the number of saved episodes.
            A latched control-server/camera fault discards the partial take and
            exits the recorder (code 1).
            """

            def _abort_for_health() -> "None":
                """A latched control-server/camera fault is fatal: discard any
                partial episode and exit the recorder with code 1. ``SystemExit``
                unwinds through the ``VideoEncodingManager`` context and
                ``record()``'s ``finally``, so the normal cleanup (encoder flush,
                dataset finalize, robot disconnect) still runs."""
                logging.warning(
                    "[HEALTH] discarding episode and exiting (server_down=%s camera_down=%s)",
                    health["server_down"],
                    health["camera_down"],
                )
                log_say("Discarding episode and exiting", cfg.play_sounds)
                dataset.clear_episode_buffer()
                raise SystemExit(1)

            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                events["start_episode"] = False
                log_say(
                    f"Manual demo {recorded_episodes + 1}/{cfg.dataset.num_episodes}: guide the arm "
                    "to the start pose, then press ENTER to record. "
                    "RIGHT ends & saves this episode; LEFT discards it; ESC quits.",
                    cfg.play_sounds,
                )
                while not events["stop_recording"]:
                    # Gripper keys stay live between takes so the operator can
                    # open/close the Hand while re-positioning the object.
                    process_gripper_key_events(robot, events)
                    manual_demo_health_tick(
                        robot=robot, health=health, recording=False, play_sounds=cfg.play_sounds
                    )
                    # A latched control-server/camera fault is fatal: the server is
                    # gone or a camera is stalled, so a take must not start (frames
                    # would be stale/garbage) and the recorder exits instead.
                    if health["server_down"] or health["camera_down"]:
                        if events["start_episode"]:
                            events["start_episode"] = False
                        _abort_for_health()
                    if events["start_episode"]:
                        break
                    time.sleep(0.05)
                if events["stop_recording"]:
                    break
                events["exit_early"] = False
                events["rerecord_episode"] = False
                ep_summary = _record_manual_demo_episode()
                if events["stop_recording"]:
                    if health["server_down"] or health["camera_down"]:
                        # Health fault ended the take (control server down / camera
                        # stalled): drop the partial episode and exit with code 1.
                        _abort_for_health()
                    # ESC pressed mid-episode: drop the partial episode instead of saving it.
                    log_say("Quitting; discarding the partial episode", cfg.play_sounds)
                    dataset.clear_episode_buffer()
                    break
                if events["rerecord_episode"]:
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    log_say("Discarding episode; record it again", cfg.play_sounds)
                    dataset.clear_episode_buffer()
                    continue
                dataset.save_episode()
                recorded_episodes += 1
                if ep_summary is not None:
                    logging.info(
                        "Episode %d saved: %.2f s, %d frames | gripper_width=%.1f mm (grasped=%d) | "
                        "joints(deg)=%s",
                        recorded_episodes,
                        ep_summary["duration_s"],
                        ep_summary["num_frames"],
                        ep_summary["gripper_width"] * 1000.0,
                        int(ep_summary["gripper_grasped"]),
                        " ".join(f"{v:+.1f}" for v in ep_summary["joints_deg"]),
                    )
                log_say(f"Episode {recorded_episodes}/{cfg.dataset.num_episodes} saved", cfg.play_sounds)
            return recorded_episodes

        with VideoEncodingManager(dataset):
            _warmup_rlt_path()
            if cfg.dataset.manual_demo_mode:
                recorded_episodes = _run_manual_demo_episodes()
            else:
                recorded_episodes = 0
                while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                    events["episode_outcome"] = None
                    log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                    _start_episode_trackers()
                    _reset_policy_for_episode()
                    _record_episode()
                    _finish_episode_trackers()
                    episode_success = _resolve_current_episode_success()
                    _notify_episode_outcome(episode_success)
                    _run_reset_loop_if_needed(recorded_episodes)
                    recorded_episodes = _finish_recorded_episode(recorded_episodes, episode_success)
    finally:
        def _save_critical_phase_intervals() -> None:
            if critical_phase_tracker is None or len(critical_phase_tracker) == 0:
                return
            import json

            intervals = critical_phase_tracker.get_intervals()
            logging.info("Critical phase labeling: %d intervals recorded.", len(intervals))
            for ep_idx, start, end, outcome in intervals:
                outcome_str = f" [{outcome}]" if outcome else ""
                logging.info("  Episode %d: frames %d-%d (%d frames)%s", ep_idx, start, end, end - start, outcome_str)
            if dataset is None:
                return
            intervals_file = dataset.root / "critical_phase_intervals.json"
            with open(intervals_file, "w") as f:
                json.dump(
                    [
                        {"episode_index": ep, "start_frame": s, "end_frame": e, "outcome": o}
                        for ep, s, e, o in intervals
                    ],
                    f,
                    indent=2,
                )
            logging.info("Critical phase intervals saved to %s", intervals_file)

        def _finalize_dataset() -> None:
            if not dataset:
                return
            dataset.finalize()
            logging.info(
                "To inspect the recorded dataset, run:\n  lerobot-dataset-report --dataset %s",
                dataset.repo_id,
            )

        def _shutdown_policy_sync() -> None:
            if policy_sync_executor is not None:
                policy_sync_executor.shutdown()

        def _disconnect_devices() -> None:
            if robot.is_connected:
                robot.disconnect()
            if teleop and teleop.is_connected:
                teleop.disconnect()

        def _stop_listener() -> None:
            if listener and hasattr(listener, "stop"):
                listener.stop()

        def _push_dataset_to_hub() -> None:
            if not cfg.dataset.push_to_hub:
                return
            if dataset is not None:
                dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)
                return
            logging.warning(
                "`dataset.push_to_hub=true` was requested, but dataset was not initialized due to an earlier error."
            )

        log_say("Stop recording", cfg.play_sounds, blocking=True)
        _finalize_dataset()
        _save_critical_phase_intervals()
        _shutdown_policy_sync()
        _disconnect_devices()
        _stop_listener()
        _push_dataset_to_hub()
        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    import os

    import av

    # Hide the SVT-AV1 "[config]" startup banner (keep warnings/errors): SVT-AV1
    # writes directly to stderr via its own svt_log(), bypassing ffmpeg logging,
    # so only the SVT_LOG env var can quiet it. Set before any episode so the
    # encoder reads it at init.
    os.environ.setdefault("SVT_LOG", "2")
    # Hide the "[mp4 ...] Starting second pass: moving the moov atom ..." INFO
    # line printed when the faststart remux finalizes each episode's mp4. This
    # is a process-global ffmpeg-level filter that survives lerobot's
    # av.logging.restore_default_callback() calls; WARNING/ERROR still print.
    av.logging.set_libav_level(av.logging.WARNING)
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
